### ISSUE TITLE
Update the README.md with what `engine` metadata does

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/stimpack#16]
### Discussed in https://github.com/rubyatscale/stimpack/discussions/14

<div type='discussions-op-text'>

<sup>Originally posted by **iMacTia** July 21, 2022</sup>
The README says that you can [make your package an engine](https://github.com/rubyatscale/stimpack#making-your-package-an-engine), but it's unclear what difference that actually makes.
Could this be clarified and/or documented?</div>

Task
---
Update README.md

**Comment by AlexEvanczuk** [comment]
@ngan Should we describe in a bit more detail what this does?
