### ISSUE TITLE
Namespaced engines: what should the namespace be?

### ISSUE THREAD

**Issue by oleg-vinted** [rubyatscale/stimpack#26]
### Problem

Since https://github.com/rubyatscale/stimpack/pull/23, Stimpack supports one-level-deep nested packs.

In case of a pack with `engine: true`, the dynamically defined `Engine` constant is namespaced by the nested directory, for example:

```
packs
└── foo
    └── bar
        ├── app
        │   ├── controllers
        │   └── models
        └── package.yml
```

This would define `Foo::Bar::Engine`. It would also do `isolate_namespace Foo::Bar`, meaning that controllers and models that belong to the engine should be namespaced by `foo/bar`, yielding paths like

`packs/foo/bar/app/controllers/foo/bar/example_controller.rb`

I had the expectation that the first level of nesting (`foo`) is only for logical grouping without any impact on namespaces.

### Proposed solution

Use only the last directory for nesting for Engine constants, i.e. make it `Bar::Engine` in the example above.

The fix seems to be pretty simple: https://github.com/oleg-vinted/stimpack/commit/ff0ac5e0709c2117c444eebfbdd3b6c9cfd0db90, I'd be happy to make a PR if you're interested.

**Comment by AlexEvanczuk** [comment]
@oleg-vinted 

Thank you for your report here, really appreciate it!

I agree – I'd expect a nested pack that is an engine to use `Bar::Engine` as the Engine constant that is created in this case. I took a look at your proposed solution and it looks great to me, and I appreciate the additional test!

Feel free to send over a PR for that whenever and I'd be happy to approve and merge it and release a new version.
